name        : hwloc
version     : 2.0.0
release     : 1
license     : BSD-3-Clause
source      :
    - https://github.com/open-mpi/hwloc/archive/hwloc-2.0.0.tar.gz : 2ee91f9ad05f7c5400d6f0143ff66f26a970ecbf9b47e5bfb273450da043c8a2
component   : programming.tools
summary     : hwloc primarily aims at helping applications with gathering information about increasingly complex parallel computing platforms
description : |
    The Hardware Locality (hwloc) software project aims at easing the process of discovering hardware resources in parallel architectures. It offers command-line tools and a C API for consulting these resources, their locality, attributes, and interconnection. hwloc primarily aims at helping high-performance computing (HPC) applications, but is also applicable to any project seeking to exploit code and/or data locality on modern computing platforms.
setup       : |
    %autogen
build       : |
    %make
install     : |
    %make_install
