name       : hwloc
version    : 2.4.0
release    : 4
source     :
    - https://download.open-mpi.org/release/hwloc/v2.4/hwloc-2.4.0.tar.bz2 : 2b1f1b4adb542911096bdceceb16270e9918908dcd884ab85c2f929c2b3838e9
license    : BSD-3-Clause
component  : programming.tools
summary    : hwloc primarily aims at helping applications with gathering information about increasingly complex parallel computing platforms
description: |
    The Hardware Locality (hwloc) software project aims at easing the process of discovering hardware resources in parallel architectures. It offers command-line tools and a C API for consulting these resources, their locality, attributes, and interconnection. hwloc primarily aims at helping high-performance computing (HPC) applications, but is also applicable to any project seeking to exploit code and/or data locality on modern computing platforms.
builddeps  :
    - pkgconfig(cairo)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
